apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: extensions
    kind: Deployment
    name: $(svcName)
    namespace: kubeflow
    version: v1beta1

resources:
- ../base

configMapGenerator:
- literals:
  - name=mnist-gcs-dist
  - modelBasePath=//export-dir
  name: mnist-map-serving
