apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.S3_ENDPOINT
  name: S3_ENDPOINT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.AWS_ENDPOINT_URL
  name: AWS_ENDPOINT_URL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.AWS_REGION
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.BUCKET_NAME
  name: BUCKET_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.S3_USE_HTTPS
  name: S3_USE_HTTPS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.S3_VERIFY_SSL
  name: S3_VERIFY_SSL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.awsSecretName
  name: awsSecretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.awsAccessKeyIDName
  name: awsAccessKeyIDName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring
- fieldref:
    fieldPath: data.awsSecretAccessKeyName
  name: awsSecretAccessKeyName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-monitoring

patchesJson6902:
- path: deployment_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: tensorboard-tb
    namespace: kubeflow
    version: v1beta1

resources:
- ../base

configMapGenerator:
- literals:
  - logDir=/tmp
  - awsSecretName=aws-creds
  - awsAccessKeyIDName=awsAccessKeyID
  - awsSecretAccessKeyName=awsSecretAccessKey
  - S3_ENDPOINT=s3.us-west-2.amazonaws.com
  - AWS_ENDPOINT_URL=https://s3.us-west-2.amazonaws.com
  - AWS_REGION=us-west-2
  - BUCKET_NAME=mybucket
  - S3_USE_HTTPS=1
  - S3_VERIFY_SSL=1
  name: mnist-map-monitoring
