apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

# TBD (jinchihe) Need move the image to base file once.
# the issue addressed: kubernetes-sigs/kustomize/issues/1040
# TBD (jinchihe) Need to update the image once
# the issue addressed: kubeflow/testing/issues/373
images:
- name: training-image
  newName: gcr.io/kubeflow-examples/mnist/model
  newTag: v20190111-v0.2-148-g313770f

vars:
- fieldref:
    fieldPath: data.S3_ENDPOINT
  name: S3_ENDPOINT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.AWS_ENDPOINT_URL
  name: AWS_ENDPOINT_URL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.AWS_REGION
  name: AWS_REGION
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.BUCKET_NAME
  name: BUCKET_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.S3_USE_HTTPS
  name: S3_USE_HTTPS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.S3_VERIFY_SSL
  name: S3_VERIFY_SSL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.awsSecretName
  name: awsSecretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.awsAccessKeyIDName
  name: awsAccessKeyIDName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.awsSecretAccessKeyName
  name: awsSecretAccessKeyName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
      
patchesJson6902:
- path: Worker_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2
- path: Ps_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2
- path: Chief_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2

resources:
- ../base

configMapGenerator:
- literals:
  - name=mnist-train-dist
  - trainSteps=200
  - batchSize=100
  - learningRate=0.01
  - modelDir=s3://path
  - exportDir=s3://export
  - awsSecretName=aws-creds
  - awsAccessKeyIDName=awsAccessKeyID
  - awsSecretAccessKeyName=awsSecretAccessKey
  - S3_ENDPOINT=s3.us-west-2.amazonaws.com
  - AWS_ENDPOINT_URL=https://s3.us-west-2.amazonaws.com
  - AWS_REGION=us-west-2
  - BUCKET_NAME=mybucket
  - S3_USE_HTTPS=1
  - S3_VERIFY_SSL=1
  name: mnist-map-training

secretGenerator:
- literals:
  - awsAccessKeyID=xxxxx
  - awsSecretAccessKey=xxxxx
  name: aws-creds
  namespace: kubeflow
  type: Opaque
