apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configurations:
- params.yaml

# TBD (jinchihe) Need move the image to base file once.
# the issue addressed: kubernetes-sigs/kustomize/issues/1040
# TBD (jinchihe) Need to update the image once
# the issue addressed: kubeflow/testing/issues/373
images:
- name: training-image
  newName: gcr.io/kubeflow-examples/mnist/model
  newTag: v20190111-v0.2-148-g313770f

vars:
- fieldref:
    fieldPath: data.pvcName
  name: pvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
- fieldref:
    fieldPath: data.pvcMountPath
  name: pvcMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: mnist-map-training
      
patchesJson6902:
- path: Worker_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2
- path: Ps_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2
- path: Chief_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    namespace: kubeflow
    version: v1beta2

resources:
- ../base

configMapGenerator:
- literals:
  - name=mnist-train-local
  - trainSteps=200
  - batchSize=100
  - learningRate=0.01
  - pvcName=local
  - pvcMountPath=/mnt
  - modelDir=/mnt
  - exportDir=/mnt/export
  name: mnist-map-training
